import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by vishn_000 on 20.01.14.
 */
public class DeliveryEventForm extends JFrame {
    private JPanel panel1;
    private JButton deliveredButton;
    private JTextField shipmentIdTextField;
    private JButton closeButton;

    public DeliveryEventForm() {
        super("Delivery event");
        $$$setupUI$$$();
        setContentPane(panel1);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        deliveredButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SendMessage sendMessage = new SendMessage();
                sendMessage.produceMessages(SendMessage.DELIVERY_QUEUE, "<deliveryEvent><shipmentId>" + shipmentIdTextField.getText() + "</shipmentId></deliveryEvent>");
            }
        });

        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TruckMenuForm truckMenuForm = new TruckMenuForm();
                setVisible(false);
            }
        });

        setVisible(true);
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Shipment Id");
        panel1.add(label1);
        shipmentIdTextField = new JTextField();
        shipmentIdTextField.setColumns(5);
        panel1.add(shipmentIdTextField);
        deliveredButton = new JButton();
        deliveredButton.setText("Delivered");
        panel1.add(deliveredButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
