import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by vishn_000 on 20.01.14.
 */
public class ExceptionEventForm extends JFrame {
    private JPanel panel1;
    private JTextField truckIdTextField;
    private JTextArea textArea1;
    private JButton sendExceptionButton;
    private JButton closeButton;

    public ExceptionEventForm() {
        super("Exception event");
        setContentPane(panel1);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        sendExceptionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SendMessage sendMessage = new SendMessage();
                sendMessage.produceMessages(SendMessage.EXCEPTION_QUEUE, "<exceptionEvent><truckId>" + truckIdTextField.getText() + "</truckId><exceptionDescription>" + textArea1.getText() + "</exceptionDescription></exceptionEvent>");
            }
        });

        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TruckMenuForm truckMenuForm = new TruckMenuForm();
                setVisible(false);
            }
        });
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("truck Id");
        panel1.add(label1);
        truckIdTextField = new JTextField();
        truckIdTextField.setColumns(5);
        panel1.add(truckIdTextField);
        final JLabel label2 = new JLabel();
        label2.setText("description");
        panel1.add(label2);
        textArea1 = new JTextArea();
        textArea1.setColumns(20);
        textArea1.setRows(3);
        panel1.add(textArea1);
        sendExceptionButton = new JButton();
        sendExceptionButton.setText("Send Exception");
        panel1.add(sendExceptionButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
