import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by vishn_000 on 20.01.14.
 */
public class PositionEventForm extends JFrame {
    private JPanel panel1;
    private JTextField truckIdTextField;
    private JTextField longTextField;
    private JTextField latTextField;
    private JButton sendPositionButton;
    private JButton closeButton;

    public PositionEventForm() {
        super("Position event");
        setContentPane(panel1);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        sendPositionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SendMessage sendMessage = new SendMessage();
                sendMessage.produceMessages(SendMessage.POSITION_QUEUE, "<positionEvent><truckId>" + truckIdTextField.getText() + "</truckId><long>" + longTextField.getText() + "</long><lat>" + latTextField.getText() + "</lat></positionEvent>");
            }
        });

        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TruckMenuForm truckMenuForm = new TruckMenuForm();
                setVisible(false);
            }
        });

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Truck Id");
        panel1.add(label1);
        truckIdTextField = new JTextField();
        truckIdTextField.setColumns(5);
        panel1.add(truckIdTextField);
        final JLabel label2 = new JLabel();
        label2.setText("Long");
        panel1.add(label2);
        longTextField = new JTextField();
        longTextField.setColumns(5);
        panel1.add(longTextField);
        final JLabel label3 = new JLabel();
        label3.setText("Lat");
        panel1.add(label3);
        latTextField = new JTextField();
        latTextField.setColumns(5);
        panel1.add(latTextField);
        sendPositionButton = new JButton();
        sendPositionButton.setText("Send Position");
        panel1.add(sendPositionButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
