import javafx.geometry.Pos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by vishn_000 on 20.01.14.
 */
public class TruckMenuForm extends JFrame {
    private JButton deliveryEventButton;
    private JPanel panel1;
    private JButton positionEventButton;
    private JButton closeButton;
    private JButton exceptionEventButton;

    public TruckMenuForm() {
        super("Truck menu");
        setContentPane(panel1);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        deliveryEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                DeliveryEventForm deliveryEventForm = new DeliveryEventForm();
            }
        });

        positionEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                PositionEventForm positionEventForm = new PositionEventForm();
            }
        });

        exceptionEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                ExceptionEventForm exceptionEventForm = new ExceptionEventForm();
            }
        });

        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        deliveryEventButton = new JButton();
        deliveryEventButton.setText("Delivery event");
        panel1.add(deliveryEventButton);
        positionEventButton = new JButton();
        positionEventButton.setText("Position event");
        panel1.add(positionEventButton);
        exceptionEventButton = new JButton();
        exceptionEventButton.setText("Exception event");
        panel1.add(exceptionEventButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
